#%RAML 1.0 NamedExample
value:
  {
    "organization": {
      "identifier": 864139442,
      "name": "Norwegian Red Cross Search and Rescue"
    },
    "department": {
      "identifier": 12,
      "name": "Hordaland Red Cross Search and Rescue District"
    },
    "section": {
      "identifier": 1200913,
      "name": "Bergen Red Cross Search and Rescue Corps"
    }
  }