#%RAML 1.0 NamedExample
value:
  {
    "organization": {
      "identifier": 864139442,
      "name": "Norwegian Red Cross Search and Rescue"
    },
    "department": {
      "identifier": 03,
      "name": "Oslo Red Cross Search and Rescue District"
    },
    "section":
    {
      "identifier": 0300903,
      "name": "Oslo Red Cross Search and Rescue Corps"
    }
  }