#%RAML 1.0 NamedExample
value:
  {
    "id": "4bddecd8-ca17-4963-9715-73421e266b00",
    "name": "Scene",
    "type": "Fact",
    "quality": "Verified",
    "description": "Incident scene",
    "address": {
      "lines": [
        "Hausmanns gate 7",
        "0186 Oslo"
      ],
      "location": {         
        "lon": 10.7558176,
        "lat": 59.9155099,
        "alt": 17
      }
    }
  } 