#%RAML 1.0 NamedExample
value:
  {
    "startAt": 0,
    "maxResults": 10,
    "total": 2,
    "incidents":
      [
        { "id": "326a54fc-60a7-4290-94ce-489e2096698d" },
        { "id": "78a13d99-0656-47a9-9d8b-ded349be9145" }
      ]
  }
