#%RAML 1.0 NamedExample
value:
  {
    "id": "6c554219-55d1-40a9-a6de-e8195347e0d4",
    "type": "Communication",
    "generated": false,
    "timestamps": [
      { 
        "name": "created",
        "datetime": "2018-01-01T15:00:00Z"
      }
    ],
    "reporter" : { 
      "id": "6645bda5-2470-45bf-9600-e310dc686f24", 
      "name": "Kari Normann",
      "function": "Incident Commander"
    },
    "sender": {
      "id": "10b8a055-3902-486a-bb1f-8c2ee6559393",
      "number": 1,
      "type": "Team"
    },
    "receiver": "Command Post",
    "description": "Team 1 started on Mission 1"
  }  