#%RAML 1.0 NamedExample
value:
  {
    "startAt": 0,
    "maxResults": 10,
    "total": 2,
    "logs":
      [
        { "id": "6c554219-55d1-40a9-a6de-e8195347e0d4" },
        { "id": "9816c850-f323-4221-98ad-597de369b397" }
      ]
  }