#%RAML 1.0 NamedExample
value:
  {
    "id": "bafb5fe0-54e2-4cae-9ce9-4ccdade6fc5d",
    "number": 1,
    "type": "Rescue",
    "priority": {
      "value": "High"
    },
    "status": {
      "value": "Planning"
    },
    "description": "Rescue mission",
    "geodata": [
      {
        "lines": [
          "Hausmanns gate 7",
          "0186 Oslo"
        ],
        "location": {
          "lon": 10.7558176,
          "lat": 59.9155099,
          "alt": 17
        }
      }
    ],
    "timestamps": [
      { 
        "name": "created",
        "datetime": "2018-01-01T15:00:00Z"
      }
    ],
    "resolution": {
      "value": "Unresolved"
    },
  }