#%RAML 1.0 NamedExample
value:
  {
    "startAt": 10,
    "maxResults": 10,
    "total": 143,
    "operations":
      [
        { "id": "5d1e7e22-b7c9-4083-875d-2a790efd934a" },
        { "id": "224606c8-c57a-4835-bb0b-0f6eafe3f91c" }
      ]
  }