#%RAML 1.0 NamedExample
value:
  {
    "id": "326a54fc-60a7-4290-94ce-489e2096698d",
    "type": "Search",
    "status": {
      "value": "OnScene"
    },
    "timestamps": [
      {
        "name": "Created",
        "datetime": "2018-01-01T15:05:00Z"
      },
      {
        "name": "Mobilizing",
        "datetime": "2018-01-01T15:15:00Z"
      },
      {
        "name": "OnScene",
        "datetime": "2018-01-01T15:45:00Z"
      }
    ]
  }