#%RAML 1.0 NamedExample
value:
  {
    "personnel": 
      [
        { 
          "id": "6645bda5-2470-45bf-9600-e310dc686f24", 
          "name": "Kari Normann",
          "managed": "locally"
        },
        { 
          "id": "7e5545b7-729c-4c8d-b99c-840dc97ac392", 
          "name": "Ola Normann",
          "managed": "remotely"
        }
      ]
  }