#%RAML 1.0 NamedExample
value:
  {
    "id": "6645bda5-2470-45bf-9600-e310dc686f24",
    "name": "Kari Normann",
    "address": {
      "lines": [
        "Stortingsgata 1",
        "0161 Oslo"
      ],
      "location": {
        "lat": 59.9141697,
        "lon": 10.7321812,
        "alt": 17
      }
    },
    "function": "Incident Commander",
    "managed": "locally",
    "affiliation": {
      "organization": {
        "identifier": 864139442,
        "name": "Norwegian Red Cross Search and Rescue"
      },
      "department": {
        "identifier": 03,
        "name": "Oslo Red Cross Search and Rescue District"
      },
      "section":
      {
        "identifier": 0300903,
        "name": "Oslo Red Cross Search and Rescue Corps"
      }
    },
    "competences": [
      {
        "name": "Operation Mananger",
        "approved": "2018-01-01"
      },
      {
        "name": "SAR Technician",
        "approved": "2018-01-01"
      }      
    ]
  }    
