#%RAML 1.0 NamedExample
value:
  {
    "id": "7e5545b7-729c-4c8d-b99c-840dc97ac392",
    "name": "Ola Normann",
    "address": {
      "lines": [
        "Stortingsgata 1",
        "0161 Oslo"
      ],
      "location": {
        "lat": 59.9141697,
        "lon": 10.7321812,
        "alt": 17
      }
    },
    "function": "Team Leader",
    "managed": "remotely",
    "affiliation": {
      "organization": {
        "identifier": 864139442,
        "name": "Norwegian Red Cross Search and Rescue"
      },
      "department": {
        "identifier": 12,
        "name": "Hordaland Red Cross Search and Rescue District"
      },
      "section": {
        "identifier": 1200913,
        "name": "Bergen Red Cross Search and Rescue Corps"
      }
    },
    "competences": [
      {
        "name": "Team Leader",
        "approved": "2018-01-01"
      },
      {
        "name": "EMT",
        "approved": "2018-01-01"
      }      
    ]
  }