#%RAML 1.0 NamedExample
value:
  {
    "tracking": [
      {
        "id": "d299c0a7-b5e1-4070-a948-9964261a68aa",
        "status": {
          "value": "active"
        },
        "unit": {
          "id": "10b8a055-3902-486a-bb1f-8c2ee6559393"
        },
        "location": {
            "timestamp": "2018-01-01T15:05:00Z",
            "point": {
              "lon": 10.7558176,
              "lat": 59.9155099,
              "alt": 17
            }
        },
        "tracks": [
          {
            "timestamp": "2018-01-01T15:05:00Z",
            "point": {
              "lon": 10.7558176,
              "lat": 59.9155099,
              "alt": 17
            }
          },
          {
            "timestamp": "2018-01-01T15:05:00Z",
            "point": {
              "lon": 10.7375841,
              "lat": 59.9131303,
              "alt": 17
            }
          }      
        ]
      }
    ]
  }