#%RAML 1.0 NamedExample
value:
  {
    "transports": 
      [
        {
          "id": "ecb7ab3e-84b7-4656-83dd-f43ed2a20b90",
          "identifier": "SN99999",
          "type": "Car"
        }, 
        {
          "id": "2bd9e09e-65aa-4612-80a7-b2959963d136",
          "identifier": "LN-GKI",
          "type": "Aircraft"
        }
      ]
  }