value:
  {
    "units":
      [
        {
          "id": "10b8a055-3902-486a-bb1f-8c2ee6559393",
          "number": 1,
          "type": "Team",
          "missions": [
            {
                "id": "bafb5fe0-54e2-4cae-9ce9-4ccdade6fc5d",
                "number": 1,
                "type": "Rescue",
                "priority": {
                  "value": "High"
                },
                "status": {
                  "value": "Planning"
                },
                "description": "Rescue mission",
                "geodata": [
                  {
                    "lines": [
                      "Hausmanns gate 7",
                      "0186 Oslo"
                    ],
                    "location": {
                      "lon": 10.7558176,
                      "lat": 59.9155099,
                      "alt": 17
                    }
                  }
                ],
                "timestamps": [
                  { 
                    "name": "created",
                    "datetime": "2018-01-01T15:00:00Z"
                  }
                ],
                "resolution": {
                  "value": "Unresolved"
                },
              },
              {
                "id": "eae9d006-f5de-4660-9b8d-e6cec1d65e8c",
                "number": 2,
                "type": "Transport",
                "priority": {
                  "value": "High"
                },
                "status": {
                  "value": "Planning"
                },
                "description": "Transport rescue teams",
                "geodata": [
                  {
                    "lines": [
                      "Hausmanns gate 7",
                      "0186 Oslo"
                    ],
                    "location": {
                      "lon": 10.7558176,
                      "lat": 59.9155099,
                      "alt": 17
                    }
                  }
                ],
                "timestamps": [
                  { 
                    "name": "created",
                    "datetime": "2018-01-01T15:00:00Z"
                  }
                ],
                "resolution": {
                  "value": "Unresolved"
                },
              }   
          ],
          "personnel": [
              { 
                "id": "6645bda5-2470-45bf-9600-e310dc686f24", 
                "name": "Kari Normann",
                "managed": "locally"
              },
              { 
                "id": "7e5545b7-729c-4c8d-b99c-840dc97ac392", 
                "name": "Ola Normann",
                "managed": "remotely"
              }
          ],
          "transports": [
              {
                "id": "ecb7ab3e-84b7-4656-83dd-f43ed2a20b90",
                "identifier": "SN99999",
                "type": "Car"
              }, 
              {
                "id": "2bd9e09e-65aa-4612-80a7-b2959963d136",
                "identifier": "LN-GKI",
                "type": "Aircraft"
              }
          ],
        }
      ]
  }