#%RAML 1.0 DataType
displayName: operation

type: !include identity.raml
properties: 
  type: 
    type: string
    required: false
    examples: 
      SAR: "Search and Rescue"
      EPS: "Centre for evacuees and relatives"
  status: 
    type: !include status.raml
    required: false
    default: 
      value:
        value: Mobilizing
    examples: 
      Mobilizing: 
        value:
          value: Mobilizing
      OnScene: 
        value:
          value: OnScene
      Demobilizing: 
        value:
          value: Demobilizing
      Closed: 
        value:
          value: Closed       
  timestamps:
    type: array
    items: !include timestamp.raml  
    required: false
  incidentId:
    type: string
    required: false