#%RAML 1.0 DataType
displayName: polygon
description: A polygon (closed line segment) is a part of a line that starts and ends in same endpoint, and contains every point on the line including both endpoints.

type: array
items: !include point.raml

