#%RAML 1.0 DataType
displayName: polyline
description: A polyline (open line segment) is a part of a line that is bounded by two distinct endpoints, and contains every point on the line between its endpoints.

type: array
items: !include point.raml

