#%RAML 1.0 ResourceType
displayName: <<resourcePathName|!singularize>>
description: <<resourcePathName|!singularize>> with `<<item_id>> = {<<item_id>>}`

uses: 
  traits: ../libraries/traits.raml

uriParameters:
  <<item_id>>: 
    type: string
    description: Globally Unique Identifier (GUID)

post:
  is: [traits.secured, traits.add_item: {example: <<example>>}]