#%RAML 1.0 Library

traits: 
  secured: !include traits/secured.raml
  add_item: !include traits/add_item.raml
  read_item: !include traits/read_item.raml
  update_item: !include traits/update_item.raml
  delete_item: !include traits/delete_item.raml
  read_collection: !include traits/read_collection.raml
  expand: !include traits/expand.raml
  searchable: !include traits/searchable.raml
  pageable: !include traits/pageable.raml
