#%RAML 1.0 Library

usage: Used by operations.raml

types:   
  identity: !include types/identity.raml
  incident: !include types/incident.raml
  clue: !include types/clue.raml
  subject: !include types/subject.raml
  person: !include types/person.raml
  vehicle: !include types/vehicle.raml
  operation: !include types/operation.raml        
  attendence: !include types/attendence.raml
  timestamp: !include types/timestamp.raml
  transition: !include types/transition.raml
  status: !include types/status.raml
  resolution: !include types/resolution.raml
  priority: !include types/priority.raml
  severity: !include types/severity.raml
  personnel: !include types/personnel.raml
  transport: !include types/transport.raml  
  affiliation: !include types/affiliation.raml  
  unit: !include types/unit.raml
  mission: !include types/mission.raml
  report: !include types/report.raml
  message: !include types/message.raml
  callout: !include types/callout.raml
  address: !include types/address.raml
  area: !include types/area.raml
  geometry: !include types/geometry.raml 
  log: !include types/log.raml
  commandpost: !include types/commandpost.raml
  competence: !include types/competence.raml
  forecast: !include types/forecast.raml
  point: !include types/point.raml
  polyline: !include types/polyline.raml
  track: !include types/track.raml
  tracking: !include types/tracking.raml
  
