#%RAML 1.0 Trait
displayName: Delete <<resourcePathName|!singularize>>
description: Delete <<resourcePathName|!singularize>> with `<<item_id>> = {<<item_id>>}`.

uses: 
  types: ../types.raml

responses:
  200:
    body:
      application/json:
        type: object
        example: 
          message: The <<resourcePathName|!singularize>> has been properly deleted
  403:
    body:
      application/json:
        type: object
        example:
          message: Forbidden - The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated.